-- ============================================================
-- Devi Youth — Sree Bala Ganesh — Push notification device tokens
-- Run AFTER 01_schema.sql and 02_policies.sql.
--
-- Stores one row per installed device (identified by its FCM
-- registration token). The app upserts its own token here every time
-- it launches natively and a token comes back (see
-- useNativeNotifications() in src/App.jsx). The send-push Edge
-- Function reads every row here with the service role key whenever a
-- new announcement or event is published, and fans a push out to
-- each token.
-- ============================================================

create table if not exists device_tokens (
  token text primary key,
  platform text not null default 'android' check (platform in ('android', 'ios', 'web')),
  lang text not null default 'en' check (lang in ('en', 'te')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_device_tokens_platform on device_tokens(platform);

alter table device_tokens enable row level security;

-- Anyone (even a signed-out villager — most of this app's users never
-- log in) can register their own device's token. There's no "own row"
-- concept to enforce here the way there is for profiles: the token
-- itself, generated by Google/FCM per install, is what identifies the
-- row, so upsert-by-token is the correct and only access pattern.
create policy "device_tokens: anyone can register a token" on device_tokens
  for insert
  with check (true);

create policy "device_tokens: anyone can refresh their own token row" on device_tokens
  for update
  using (true)
  with check (true);

-- Deliberately no SELECT or DELETE policy for anon/authenticated: the
-- list of tokens is only ever read by send-push using the service
-- role key, which bypasses RLS entirely. Villagers' devices should
-- never be enumerable from the client.

-- Keep updated_at current on every upsert-refresh, so stale tokens
-- (e.g. an uninstalled app that never comes back) are easy to spot
-- and prune later if the table grows large.
create or replace function touch_device_token_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_device_token_update on device_tokens;
create trigger on_device_token_update
  before update on device_tokens
  for each row execute function touch_device_token_updated_at();
